"""empty message

Revision ID: 010c7f92ed95
Revises: a30daf3d9b41
Create Date: 2025-01-13 18:52:19.541447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010c7f92ed95'
down_revision = 'a30daf3d9b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicles_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
